# Treat Pre-conditions
if [[ -z $1 ]]; then
    # Enable (or not) THEME_POWERLINE themes
    export THEME_POWERLINE=${THEME_POWERLINE:-true}
    export POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    export POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
    export POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%{%F{245}%}\u250f"
    export POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%{%F{245}%}\u2517%{%F{default}%} "
    export POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
    export POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
    export POWERLEVEL9K_OS_ICON_BACKGROUND="235"
    export POWERLEVEL9K_OS_ICON_FOREGROUND="249"
    export POWERLEVEL9K_DIR_HOME_FOREGROUND="253"
    export POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="235"
    export POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="235"
    export POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="249"
    export POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="235"
    export POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="249"
    export POWERLEVEL9K_STATUS_OK_BACKGROUND="235"
    export POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
    export POWERLEVEL9K_STATUS_ERROR_BACKGROUND="235"
    export POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
    export POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND="235"
    export POWERLEVEL9K_LOAD_WARNING_BACKGROUND="235"
    export POWERLEVEL9K_LOAD_NORMAL_BACKGROUND="235"
    export POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND="249"
    export POWERLEVEL9K_LOAD_WARNING_FOREGROUND="249"
    export POWERLEVEL9K_LOAD_NORMAL_FOREGROUND="249"
    export POWERLEVEL9K_LOAD_CRITICAL_VISUAL_IDENTIFIER_COLOR="red"
    export POWERLEVEL9K_LOAD_WARNING_VISUAL_IDENTIFIER_COLOR="yellow"
    export POWERLEVEL9K_LOAD_NORMAL_VISUAL_IDENTIFIER_COLOR="green"
    export POWERLEVEL9K_RAM_BACKGROUND="235"
    export POWERLEVEL9K_RAM_FOREGROUND="249"
    export POWERLEVEL9K_RAM_ELEMENTS=(ram_free)
    export POWERLEVEL9K_TIME_BACKGROUND="235"
    export POWERLEVEL9K_TIME_FOREGROUND="249"
    export POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S} \UE12E"
    export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=('os_icon' 'context' 'dir' 'vcs')
    export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('status' 'load' 'ram_joined' 'time')

# Treat Post-conditions
elif [[ $1 == "POST" ]]
then
    # zsh-autosuggestions config
    export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=9'

    # zsh-history-substring-search key bindings
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down

fi
